function lq = LowerBound(W0, v0, W, v, n, D, beta0, H, S, J)
lq = log(B(W0,v0,D)+1e-100) - log(B(W,v,D)+1e-100) - .5*(n*D*log(2*pi) - D*log(beta0) - ...
    v*D + log(det(H)) + v*trace(S*W) + v*trace(pinv(W0)*W) + ...
    ((beta0*n*v)/(beta0+n))*trace(J*W));
end